package com.recoyx.sxc.semantics;

public enum ConversionKind
{
    COVARIANT_VECTOR,
    CONTRAVARIANT_VECTOR,
    NUMERIC_FROM_NUMERIC,
    ENUM_NUMBER,
    NUMBER_FROM_ENUM,
    ANY,
    FROM_ANY,
    FROM_STRING,
    STRING,
    IMPLEMENTED_INTERFACE,
    SUPER_CLASS,
    SUBCLASS,
    SUPER_INTERFACE,
    SUB_INTERFACE,
    FROM_NULLABLE,
    NULLABLE,
    FROM_NON_NULLABLE,
    IMPLEMENTOR,
    FROM_TYPE_PARAMETER,
    TO_TYPE_PARAMETER,
    NON_NULLABLE,
    FROM_VERIFYING_TYPE,
    TO_VERIFYING_TYPE
}